gazebo:
  - '11'
ogre:
  - 1.10.12
setuptools:
  - 69
numpy:
  - 1.25.*
libprotobuf:
  - 5.28.*
protobuf:
  - 5.28.*
spdlog:
  - 1.14
qt_main:
  - 5.15.*
pyqt:
  - 5.15.*
pyqtwebengine:
  - 5.*
pyqtchart:
  - 5.*
tinyxml2:
  - 9.*
cmake:
  - 3.*
libopencv:
  - 4.8.*
opencv:
  - 4.8.*
ffmpeg:
  - 6.*
libxml2:
  - 2.13.*
icu:
  - 74.*
graphviz:
  - 8.*
sip:
  - 6.*

cdt_name:
  - ${{ "cos7" if linux }}

python:
  - 3.10.15 *_cpython
python_impl:
  - cpython

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
c_compiler_version:            # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
cxx_compiler_version:          # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
